<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <NoWarn>NETSDK1138</NoWarn><!-- supress 'net6.0' is out of support warning -->
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Lib.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>
